### ISSUE TITLE
.ass exporter not working properly on latest version of Blender (4.4.0)

### ISSUE THREAD

**Issue by fable-law-458** [General-101/Halo-Asset-Blender-Development-Toolset#103]
When exporting an .ass file in the new current blender version, it results in error messages inside blender's info log prompting:

Python: Traceback (most recent call last):
  File "C:\Users\fable\AppData\Roaming\Blender Foundation\Blender\4.4\extensions\blender_org\Modifier_List_Fork\modules\ui\sidebar.py", line 89, in poll
    if not prefs.use_sidebar:
           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'use_sidebar'

**Comment by General-101** [comment]
Will give it a look when I can

**Comment by General-101** [comment]
That error log seems unrelated to my addon now that I look at it. The Halo Blender toolset also seems to work fine on 4.4 for me. Please disable all other addons you have on your end. If you're sure that this error is related to the toolset still please upload your crashlog. You can find them in your user profile on your machine

C:\Users\Steven\blender_halo_crashes

For example.

**Comment by fable-law-458** [comment]
Ok, we'll do. I'll double check.

**Comment by fable-law-458** [comment]
I've tried turning off add-on's that may conflict with the halo blender toolset, but no luck on my end. Here's the crash log:

[traceback.txt](https://github.com/user-attachments/files/19405479/traceback.txt)

**Comment by General-101** [comment]
That's an error from Blender 4.3 while reading a scenario. Do you have one from 4.4?

**Comment by General-101** [comment]
Though that does seem like a real error and I think I see how you ran into that.

**Comment by fable-law-458** [comment]
I tried to see if it spit out something in the new version of Blender with the directory you had me look for, I guess it didn't upload anything new crash reports for Blender 4.4. I'm not sure where else to look at to see other hints of why I'm having this issue. But here's an image of my outliner and the attributes panel if there's something I might have overlooked.

![Image](https://github.com/user-attachments/assets/06d1ee72-1c7d-4229-ab2c-b920c4a66014)

**Comment by fable-law-458** [comment]
I've made this .blend file originally in Blender 4.3 before 4.4 released. I'm not sure if it's something outdated that the add-on doesn't like.

**Comment by General-101** [comment]
upload the blend and I'll see if I can reproduce on my end

**Comment by fable-law-458** [comment]
Hmm, apparently I guess my Blender may be messed up. When I saved my .blend file the same thing comes up. That's odd... But it does save the blend file correctly. If you like to DM me in Discord, that's fine.

**Comment by General-101** [comment]
Asked the user to delete their files in 

C:\Users\Steven\AppData\Roaming\Blender Foundation\Blender

That seems to have fixed the issue. Likely another addon/extension triggering something. Either way closing.
